import { resolve } from "node:path";
import { defineConfig } from "vite";

// Multi-page static build: the gallery index links out to each component's
// own standalone HTML page (so a developer can open/copy a single component
// page in isolation, per each user story's "Independent Test" requirement).
export default defineConfig({
  root: ".",
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
        button: resolve(__dirname, "src/components/button/button.html"),
        textInput: resolve(__dirname, "src/components/text-input/text-input.html"),
        badge: resolve(__dirname, "src/components/badge/badge.html"),
        checkbox: resolve(__dirname, "src/components/checkbox/checkbox.html"),
        radio: resolve(__dirname, "src/components/radio/radio.html"),
        select: resolve(__dirname, "src/components/select/select.html"),
        toggle: resolve(__dirname, "src/components/toggle/toggle.html"),
        modal: resolve(__dirname, "src/components/modal/modal.html"),
        toast: resolve(__dirname, "src/components/toast/toast.html"),
        slideOver: resolve(__dirname, "src/components/slide-over/slide-over.html"),
        breadcrumbs: resolve(__dirname, "src/components/breadcrumbs/breadcrumbs.html"),
        accordion: resolve(__dirname, "src/components/accordion/accordion.html"),
        tabs: resolve(__dirname, "src/components/tabs/tabs.html"),
        dropdownMenu: resolve(__dirname, "src/components/dropdown-menu/dropdown-menu.html"),
        avatar: resolve(__dirname, "src/components/avatar/avatar.html"),
        card: resolve(__dirname, "src/components/card/card.html"),
        alert: resolve(__dirname, "src/components/alert/alert.html"),
        pagination: resolve(__dirname, "src/components/pagination/pagination.html"),
        sidebar: resolve(__dirname, "src/components/sidebar/sidebar.html"),
        navbar: resolve(__dirname, "src/components/navbar/navbar.html"),
        combobox: resolve(__dirname, "src/components/combobox/combobox.html"),
        commandPalette: resolve(__dirname, "src/components/command-palette/command-palette.html"),
        list: resolve(__dirname, "src/components/list/list.html"),
        table: resolve(__dirname, "src/components/table/table.html"),
        textarea: resolve(__dirname, "src/components/textarea/textarea.html"),
        divider: resolve(__dirname, "src/components/divider/divider.html"),
        kbd: resolve(__dirname, "src/components/kbd/kbd.html"),
        skeleton: resolve(__dirname, "src/components/skeleton/skeleton.html"),
        tooltip: resolve(__dirname, "src/components/tooltip/tooltip.html"),
        progress: resolve(__dirname, "src/components/progress/progress.html"),
        buttonGroup: resolve(__dirname, "src/components/button-group/button-group.html"),
        emptyState: resolve(__dirname, "src/components/empty-state/empty-state.html"),
        popover: resolve(__dirname, "src/components/popover/popover.html"),
        contextMenu: resolve(__dirname, "src/components/context-menu/context-menu.html"),
        composedExample: resolve(
          __dirname,
          "src/components/composed-example/composed-example.html",
        ),
        spinner: resolve(__dirname, "src/components/spinner/spinner.html"),
        aspectRatio: resolve(__dirname, "src/components/aspect-ratio/aspect-ratio.html"),
        indicator: resolve(__dirname, "src/components/indicator/indicator.html"),
        dataList: resolve(__dirname, "src/components/data-list/data-list.html"),
        slider: resolve(__dirname, "src/components/slider/slider.html"),
        stepper: resolve(__dirname, "src/components/stepper/stepper.html"),
        fileInput: resolve(__dirname, "src/components/file-input/file-input.html"),
        timeline: resolve(__dirname, "src/components/timeline/timeline.html"),
        statCard: resolve(__dirname, "src/components/stat-card/stat-card.html"),
        pinInput: resolve(__dirname, "src/components/pin-input/pin-input.html"),
        dashboardExample: resolve(
          __dirname,
          "src/components/dashboard-example/dashboard-example.html",
        ),
        treeView: resolve(__dirname, "src/components/tree-view/tree-view.html"),
        rating: resolve(__dirname, "src/components/rating/rating.html"),
        menubar: resolve(__dirname, "src/components/menubar/menubar.html"),
        colorInput: resolve(__dirname, "src/components/color-input/color-input.html"),
        settingsExample: resolve(
          __dirname,
          "src/components/settings-example/settings-example.html",
        ),
        themeGallery: resolve(__dirname, "src/components/theme-gallery/theme-gallery.html"),
        chart: resolve(__dirname, "src/components/chart/chart.html"),
        cpfInput: resolve(__dirname, "src/components/cpf-input/cpf-input.html"),
        cnpjInput: resolve(__dirname, "src/components/cnpj-input/cnpj-input.html"),
        cepInput: resolve(__dirname, "src/components/cep-input/cep-input.html"),
        phoneBrInput: resolve(__dirname, "src/components/phone-br-input/phone-br-input.html"),
        tituloEleitorInput: resolve(__dirname, "src/components/titulo-eleitor-input/titulo-eleitor-input.html"),
        pisPasepInput: resolve(__dirname, "src/components/pis-pasep-input/pis-pasep-input.html"),
        vehiclePlateInput: resolve(__dirname, "src/components/vehicle-plate-input/vehicle-plate-input.html"),
        ibanInput: resolve(__dirname, "src/components/iban-input/iban-input.html"),
        cardNumberInput: resolve(__dirname, "src/components/card-number-input/card-number-input.html"),
        phoneIntlInput: resolve(__dirname, "src/components/phone-intl-input/phone-intl-input.html"),
        dataTable: resolve(__dirname, "src/components/data-table/data-table.html"),
        numberInput: resolve(__dirname, "src/components/number-input/number-input.html"),
        passwordInput: resolve(__dirname, "src/components/password-input/password-input.html"),
        multiSelect: resolve(__dirname, "src/components/multi-select/multi-select.html"),
        actionIcon: resolve(__dirname, "src/components/action-icon/action-icon.html"),
        copyButton: resolve(__dirname, "src/components/copy-button/copy-button.html"),
        splitButton: resolve(__dirname, "src/components/split-button/split-button.html"),
        avatarGroup: resolve(__dirname, "src/components/avatar-group/avatar-group.html"),
        highlight: resolve(__dirname, "src/components/highlight/highlight.html"),
        code: resolve(__dirname, "src/components/code/code.html"),
        colorSwatch: resolve(__dirname, "src/components/color-swatch/color-swatch.html"),
        navLink: resolve(__dirname, "src/components/nav-link/nav-link.html"),
        anchor: resolve(__dirname, "src/components/anchor/anchor.html"),
        collapse: resolve(__dirname, "src/components/collapse/collapse.html"),
        spoiler: resolve(__dirname, "src/components/spoiler/spoiler.html"),
        stack: resolve(__dirname, "src/components/stack/stack.html"),
        group: resolve(__dirname, "src/components/group/group.html"),
        center: resolve(__dirname, "src/components/center/center.html"),
        container: resolve(__dirname, "src/components/container/container.html"),
        paper: resolve(__dirname, "src/components/paper/paper.html"),
        grid: resolve(__dirname, "src/components/grid/grid.html"),
        simpleGrid: resolve(__dirname, "src/components/simple-grid/simple-grid.html"),
        flex: resolve(__dirname, "src/components/flex/flex.html"),
        appShell: resolve(__dirname, "src/components/app-shell/app-shell.html"),
        ringProgress: resolve(__dirname, "src/components/ring-progress/ring-progress.html"),
        semiCircleProgress: resolve(
          __dirname,
          "src/components/semi-circle-progress/semi-circle-progress.html",
        ),
        notificationCenter: resolve(
          __dirname,
          "src/components/notification-center/notification-center.html",
        ),
        passwordStrengthMeter: resolve(
          __dirname,
          "src/components/password-strength-meter/password-strength-meter.html",
        ),
        sessionTimeoutModal: resolve(
          __dirname,
          "src/components/session-timeout-modal/session-timeout-modal.html",
        ),
        offlineBanner: resolve(__dirname, "src/components/offline-banner/offline-banner.html"),
        twoFactorReminderBanner: resolve(
          __dirname,
          "src/components/two-factor-reminder-banner/two-factor-reminder-banner.html",
        ),
        maintenanceBanner: resolve(
          __dirname,
          "src/components/maintenance-banner/maintenance-banner.html",
        ),
        darkModeToggle: resolve(__dirname, "src/components/dark-mode-toggle/dark-mode-toggle.html"),
        teamSwitcher: resolve(__dirname, "src/components/team-switcher/team-switcher.html"),
        languageSwitcher: resolve(
          __dirname,
          "src/components/language-switcher/language-switcher.html",
        ),
        scrollFeedback: resolve(__dirname, "src/components/scroll-feedback/scroll-feedback.html"),
        onboardingTour: resolve(__dirname, "src/components/onboarding-tour/onboarding-tour.html"),
        affix: resolve(__dirname, "src/components/affix/affix.html"),
        loadingOverlay: resolve(__dirname, "src/components/loading-overlay/loading-overlay.html"),
        bottomSheet: resolve(__dirname, "src/components/bottom-sheet/bottom-sheet.html"),
        themeIcon: resolve(__dirname, "src/components/theme-icon/theme-icon.html"),
        blockquote: resolve(__dirname, "src/components/blockquote/blockquote.html"),
        backgroundImage: resolve(
          __dirname,
          "src/components/background-image/background-image.html",
        ),
        watermark: resolve(__dirname, "src/components/watermark/watermark.html"),
        overflowList: resolve(__dirname, "src/components/overflow-list/overflow-list.html"),
        rollingNumber: resolve(__dirname, "src/components/rolling-number/rolling-number.html"),
        pickList: resolve(__dirname, "src/components/pick-list/pick-list.html"),
        gallery: resolve(__dirname, "src/components/gallery/gallery.html"),
        compare: resolve(__dirname, "src/components/compare/compare.html"),
        socialLogin: resolve(__dirname, "src/components/social-login/social-login.html"),
        tagsInput: resolve(__dirname, "src/components/tags-input/tags-input.html"),
        autocomplete: resolve(__dirname, "src/components/autocomplete/autocomplete.html"),
        mentions: resolve(__dirname, "src/components/mentions/mentions.html"),
        cascader: resolve(__dirname, "src/components/cascader/cascader.html"),
        treeSelect: resolve(__dirname, "src/components/tree-select/tree-select.html"),
        inputMask: resolve(__dirname, "src/components/input-mask/input-mask.html"),
        jsonInput: resolve(__dirname, "src/components/json-input/json-input.html"),
        rangeSlider: resolve(__dirname, "src/components/range-slider/range-slider.html"),
        floatLabel: resolve(__dirname, "src/components/float-label/float-label.html"),
      },
    },
  },
  server: {
    port: 5173,
  },
});
