// Single source of truth for this design system's ratified color, border-
// radius, and font-family tokens (.specify/memory/constitution.md's Base
// Semantic Palette). Both the root tailwind.config.ts (static gallery) and
// packages/react/tailwind.config.ts (React package) import this file rather
// than each declaring the same literals inline — a direct extraction, not a
// new schema, of what tailwind.config.ts already had (feature 004's
// research.md: two independently hand-typed copies of the same hex values
// is exactly the kind of drift this project's own /speckit-analyze passes
// have caught repeatedly).
//
// Values are RGB triplets (not hex) consumed via `rgb(var(--color-x) /
// <alpha-value>)` in tailwind.config.ts (feature 017 research.md R1). This
// is what lets `src/styles/themes.css` swap every token's actual color at
// runtime via a `[data-theme="..."]` custom-property block, while Tailwind
// opacity modifiers (`bg-success/5`) keep working correctly — a plain
// `var(--x)` without the RGB-tuple decomposition would break those
// modifiers. The "light" theme below is the pure-refactor baseline: same
// values as the previous hex literals, just re-expressed as RGB triplets.
export const colors = {
  brand: {
    light: "rgb(var(--color-brand-light) / <alpha-value>)",
    DEFAULT: "rgb(var(--color-brand) / <alpha-value>)",
    dark: "rgb(var(--color-brand-dark) / <alpha-value>)",
  },
  neutral: {
    50: "rgb(var(--color-neutral-50) / <alpha-value>)",
    100: "rgb(var(--color-neutral-100) / <alpha-value>)",
    200: "rgb(var(--color-neutral-200) / <alpha-value>)",
    300: "rgb(var(--color-neutral-300) / <alpha-value>)",
    400: "rgb(var(--color-neutral-400) / <alpha-value>)",
    500: "rgb(var(--color-neutral-500) / <alpha-value>)",
    600: "rgb(var(--color-neutral-600) / <alpha-value>)",
    700: "rgb(var(--color-neutral-700) / <alpha-value>)",
    800: "rgb(var(--color-neutral-800) / <alpha-value>)",
    900: "rgb(var(--color-neutral-900) / <alpha-value>)",
  },
  success: {
    DEFAULT: "rgb(var(--color-success) / <alpha-value>)",
    strong: "rgb(var(--color-success-strong) / <alpha-value>)",
  },
  warning: {
    DEFAULT: "rgb(var(--color-warning) / <alpha-value>)",
    strong: "rgb(var(--color-warning-strong) / <alpha-value>)",
  },
  error: {
    DEFAULT: "rgb(var(--color-error) / <alpha-value>)",
    strong: "rgb(var(--color-error-strong) / <alpha-value>)",
  },
  info: {
    DEFAULT: "rgb(var(--color-info) / <alpha-value>)",
    strong: "rgb(var(--color-info-strong) / <alpha-value>)",
  },
};

// Fixed, provider-mandated brand identifiers (feature 035, research.md
// R2 / plan.md Complexity Tracking). Deliberately NOT part of `colors`
// above — every value there is a CSS-custom-property indirection that
// swaps per `[data-theme]`; these must render identically regardless
// of the host app's selected curated theme, since they represent
// externally mandated brand marks (Google's "G", Facebook's blue,
// etc.), not this catalog's own swappable palette. Plain hex literals,
// consumed directly by SocialLoginGroup's icon components (SVG `fill`
// attributes) on both surfaces — never through a `bg-*`/`text-*`
// Tailwind class, since brand color is confined to the icon glyph only
// (research.md R1); the button surface itself always uses the existing
// `neutral-50`/`neutral-900` (or, for Apple/GitHub's optional
// monochrome appearance, the existing `neutral-900`/white) semantic
// tokens, never a provider-specific fill.
export const providerBrand = {
  google: { blue: "#4285F4", green: "#34A853", yellow: "#FBBC05", red: "#EA4335" },
  apple: { black: "#000000", white: "#FFFFFF" },
  facebook: { blue: "#1877F2" },
  microsoft: { red: "#F25022", green: "#7FBA00", blue: "#00A4EF", yellow: "#FFB900" },
  github: { black: "#171515" },
  // Example custom-provider accents used by this catalog's own demo/
  // preview content (research.md R7) — not a governed preset; a real
  // consumer of the custom-entry API supplies their own `color`.
  instagram: "#E1306C",
  tiktok: "#000000",
  discord: "#5865F2",
} as const;

export const borderRadius = {
  sm: "0.25rem", // 4px — inputs/checkboxes/small tags
  md: "0.5rem", // 8px — buttons/dropdowns/secondary navigation
  lg: "0.75rem", // 12px — cards/modals/panels/primary containers
  full: "9999px", // pills/circles — toggle tracks/dots, avatars
};

export const fontFamily = {
  sans: ["Inter", "system-ui", "sans-serif"],
  mono: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
};

// The complete set of --color-* custom properties every theme block in
// src/styles/themes.css MUST declare (feature 017 contracts/theme-tokens
// .contract.md's completeness requirement, enforced by
// scripts/check-contrast.mjs's T009a check). 21 properties total.
export const REQUIRED_THEME_PROPERTIES = [
  "--color-brand-light",
  "--color-brand",
  "--color-brand-dark",
  "--color-neutral-50",
  "--color-neutral-100",
  "--color-neutral-200",
  "--color-neutral-300",
  "--color-neutral-400",
  "--color-neutral-500",
  "--color-neutral-600",
  "--color-neutral-700",
  "--color-neutral-800",
  "--color-neutral-900",
  "--color-success",
  "--color-success-strong",
  "--color-warning",
  "--color-warning-strong",
  "--color-error",
  "--color-error-strong",
  "--color-info",
  "--color-info-strong",
];

// Feature 017 (Curated Theme Presets) — the hex source of truth for every
// theme's palette. scripts/check-contrast.mjs audits these hex values
// directly (loops PAIRINGS/RING_PAIRINGS per theme); src/styles/themes.css's
// RGB-triplet `[data-theme="..."]` blocks are hand-derived from these same
// values and MUST stay in sync (T009a's completeness check + the contrast
// audit are what catch drift, not a build-time codegen step — see
// research.md R1/R2 for why the CSS layer is authored directly rather than
// generated).
export interface ThemeTokens {
  "brand-light": string;
  brand: string;
  "brand-dark": string;
  "neutral-50": string;
  "neutral-100": string;
  "neutral-200": string;
  "neutral-300": string;
  "neutral-400": string;
  "neutral-500": string;
  "neutral-600": string;
  "neutral-700": string;
  "neutral-800": string;
  "neutral-900": string;
  success: string;
  "success-strong": string;
  warning: string;
  "warning-strong": string;
  error: string;
  "error-strong": string;
  info: string;
  "info-strong": string;
}

export interface ThemeDefinition {
  id: string;
  displayName: string;
  moodFamily: string;
  sourceReference: string;
  isDefault?: boolean;
  tokens: ThemeTokens;
}

// The 7 mood-family categories research.md R3 curated the 42-theme
// selection from, in display order — the single source of truth both
// src/components/theme-gallery/theme-gallery.html's section headings AND
// every ThemeDefinition.moodFamily value must match exactly, so a typo in
// either place can't silently create an 8th "family" or leave a section
// permanently empty.
export const MOOD_FAMILIES = [
  "Light Professional",
  "Warm/Organic Light",
  "Nature/Earth",
  "Cool/Tech Minimal",
  "Dark Moody/Professional",
  "Dark Vibrant/Expressive",
  "Distinctive/Characterful",
] as const;

export const THEMES: ThemeDefinition[] = [
  {
    id: "light",
    displayName: "Light",
    moodFamily: "Light Professional",
    sourceReference:
      "This design system's original, pre-existing default palette — the pure-refactor baseline for feature 017's architecture migration.",
    isDefault: true,
    tokens: {
      "brand-light": "#E6F0FF",
      brand: "#0066FF",
      "brand-dark": "#004BB3",
      // neutral-50 is the theme-invertible "surface/page background" role
      // (feature 017 research.md addendum, found during implementation:
      // nothing in the original 21 tokens controlled the page's own
      // background — every component hardcoded literal `bg-white` — which
      // would leave dark themes with dark accent colors on an unchanged
      // white page). Set to true white here so this retrofit is a zero-
      // visual-change rename for the pre-existing light theme; the
      // "subtle highlight, one step off the page background" role that
      // USED to live at neutral-50 (#F9FAFB) moved to neutral-100.
      "neutral-50": "#FFFFFF",
      "neutral-100": "#F3F4F6",
      "neutral-200": "#E5E7EB",
      "neutral-300": "#D1D5DB",
      "neutral-400": "#9CA3AF",
      "neutral-500": "#6B7280",
      "neutral-600": "#4B5563",
      "neutral-700": "#374151",
      "neutral-800": "#1F2937",
      "neutral-900": "#111827",
      success: "#10B981",
      "success-strong": "#065F46",
      warning: "#F59E0B",
      "warning-strong": "#78350F",
      error: "#EF4444",
      "error-strong": "#991B1B",
      info: "#3B82F6",
      "info-strong": "#1E40AF",
    },
  },
  {
    id: "corporate",
    displayName: "Corporate",
    moodFamily: "Light Professional",
    sourceReference:
      "DaisyUI v5's real, live-fetched corporate.css (packages/daisyui/src/themes/corporate.css) — primary/base/semantic OKLCH values used verbatim as anchors; the neutral-50..900 ramp is OKLCH-interpolated between the real base-100 and base-content anchors (research.md R6, eased t^0.8 for AAA headroom at the mid stops); brand-light/brand/brand-dark/*-strong are derived from the real primary/status OKLCH values by searching for the closest in-gamut lightness that clears this catalog's AAA/WCAG-1.4.11 thresholds against their actual shipped context (see the *-strong dual-role note on 'forest' below), converted to sRGB via a real browser engine (Chromium canvas + 2D context pixel readback, not hand-approximated OKLab math).",
    tokens: {
      "brand-light": "#DFE9F2",
      brand: "#0075C1",
      "brand-dark": "#005795",
      "neutral-50": "#FFFFFF",
      "neutral-100": "#D6D2D4",
      "neutral-200": "#B7B1B6",
      "neutral-300": "#9C959C",
      "neutral-400": "#837C85",
      "neutral-500": "#6B6570",
      "neutral-600": "#54505D",
      "neutral-700": "#3F3C4B",
      "neutral-800": "#2B2A3A",
      "neutral-900": "#181A2A",
      success: "#00A43B",
      "success-strong": "#006000",
      warning: "#FDC700",
      "warning-strong": "#7D4900",
      error: "#F85C60",
      "error-strong": "#A90020",
      info: "#0090B5",
      "info-strong": "#00597D",
    },
  },
  {
    id: "forest",
    displayName: "Forest",
    moodFamily: "Nature/Earth",
    sourceReference:
      "DaisyUI v5's real, live-fetched forest.css — same derivation method as Corporate above. A dark theme (base-100 L=20.84%, color-scheme: dark). KNOWN LIMITATION found during derivation, applies to every dark theme in this batch (forest/dracula/business): this catalog's fixed 21-token schema uses success/warning/error/info-strong (and brand-dark) in two roles that invert for a dark theme — ink-colored TEXT read directly against the page (Badge/Alert/Text-Input-error/Kbd/etc.) needs to be LIGHT on a dark page, but Indicator's solid-fill-behind-white-text usage needs the SAME token to stay DARK. One value can't satisfy both for a genuinely dark theme; the ink-on-page role won (Badge/Alert are far more widely used across this catalog), so Indicator's white-on-*-strong text fails AAA (and in some cases AA) for this theme specifically — a real, deliberate, documented trade-off, not an oversight. brand-dark is the one exception: derived toward the WHITE-TEXT role instead, since Button primary is this catalog's single most central component and must never render invisible white-on-light-fill text.",
    tokens: {
      "brand-light": "#EDF9EE",
      brand: "#1FB854",
      "brand-dark": "#006410",
      "neutral-50": "#1B1717",
      "neutral-100": "#353131",
      "neutral-200": "#4A4646",
      "neutral-300": "#5D5A5A",
      "neutral-400": "#706D6D",
      "neutral-500": "#838080",
      "neutral-600": "#959292",
      "neutral-700": "#A7A5A5",
      "neutral-800": "#B9B7B7",
      "neutral-900": "#CAC9C9",
      success: "#00A96E",
      "success-strong": "#33C386",
      warning: "#FFBE00",
      "warning-strong": "#FFC500",
      error: "#FF5861",
      "error-strong": "#FF8286",
      info: "#00B5FF",
      "info-strong": "#00BCFF",
    },
  },
  {
    id: "nord",
    displayName: "Nord",
    moodFamily: "Cool/Tech Minimal",
    sourceReference:
      "DaisyUI v5's real, live-fetched nord.css (its light re-interpretation, per research.md R6's explicit either-is-valid note) — same derivation method as Corporate above. The derived neutral-50 (#ECEFF4) and neutral-900 (#2E3440) converge almost exactly on the original standalone Nord project's own real published \"Snow Storm\"/\"Polar Night\" hex values (nordtheme.com/docs/colors-and-palettes), cross-validating the derivation method.",
    tokens: {
      "brand-light": "#DCE0E5",
      brand: "#476993",
      "brand-dark": "#324D6F",
      "neutral-50": "#ECEFF4",
      "neutral-100": "#C8CCD2",
      "neutral-200": "#AEB2BA",
      "neutral-300": "#979CA4",
      "neutral-400": "#828790",
      "neutral-500": "#6F757E",
      "neutral-600": "#5D636D",
      "neutral-700": "#4D525D",
      "neutral-800": "#3D434E",
      "neutral-900": "#2E3440",
      success: "#A3BE8D",
      "success-strong": "#3B5225",
      warning: "#EBCB8B",
      "warning-strong": "#624600",
      error: "#BF616A",
      "error-strong": "#832C39",
      info: "#B48EAD",
      "info-strong": "#5F3E5A",
    },
  },
  {
    id: "dracula",
    displayName: "Dracula",
    moodFamily: "Dark Vibrant/Expressive",
    sourceReference:
      "DaisyUI v5's real, live-fetched dracula.css (its own OKLCH re-expression, per research.md R6's explicit either-is-valid note) — same derivation method as Corporate above. The derived neutral-50 (#282A36) and brand DEFAULT (#FF79C6) converge almost exactly on the original standalone Dracula project's own real published background/pink hex values (draculatheme.com/contribute), cross-validating the derivation method. Same Indicator-vs-Badge dual-role limitation as 'forest' above (dark theme, ink-on-page role prioritized for *-strong).",
    tokens: {
      "brand-light": "#FFF0F7",
      brand: "#FF79C6",
      "brand-dark": "#962C6D",
      "neutral-50": "#282A36",
      "neutral-100": "#424B54",
      "neutral-200": "#58646A",
      "neutral-300": "#6E7C7D",
      "neutral-400": "#869290",
      "neutral-500": "#9DA7A3",
      "neutral-600": "#B4BCB6",
      "neutral-700": "#CBD0CA",
      "neutral-800": "#E2E4DE",
      "neutral-900": "#F8F8F3",
      success: "#51FA7B",
      "success-strong": "#59FF82",
      warning: "#F1FA8C",
      "warning-strong": "#F8FF93",
      error: "#FF5555",
      "error-strong": "#FFA79F",
      info: "#8BE9FD",
      "info-strong": "#92F0FF",
    },
  },
  {
    id: "business",
    displayName: "Business",
    moodFamily: "Dark Moody/Professional",
    sourceReference:
      "DaisyUI v5's real, live-fetched business.css — same derivation method as Corporate above. A dark theme (base-100 L=24.35%, color-scheme: dark). Same Indicator-vs-Badge dual-role limitation as 'forest' above (dark theme, ink-on-page role prioritized for *-strong).",
    tokens: {
      "brand-light": "#F0F6FC",
      brand: "#5D8FC6",
      "brand-dark": "#315A85",
      "neutral-50": "#202020",
      "neutral-100": "#3A3A3A",
      "neutral-200": "#4E4E4E",
      "neutral-300": "#626262",
      "neutral-400": "#747474",
      "neutral-500": "#868686",
      "neutral-600": "#989898",
      "neutral-700": "#AAAAAA",
      "neutral-800": "#BCBCBC",
      "neutral-900": "#CDCDCD",
      success: "#6BB187",
      "success-strong": "#7EC499",
      warning: "#DBAE5A",
      "warning-strong": "#E1B460",
      error: "#B94B3D",
      "error-strong": "#FF8F7E",
      info: "#0291D5",
      "info-strong": "#4DBEFF",
    },
  },
  {
    id: "cosmo",
    displayName: "Cosmo",
    moodFamily: "Light Professional",
    sourceReference:
      "Bootswatch's real, live-fetched cosmo/_variables.scss. Same derivation method as Corporate/Forest/Nord/Dracula/Business (feature 017 Phase 4). Neutral scale is Bootstrap's own real gray-100..900 (Bootswatch overrides none of them, so these are Bootstrap's framework defaults), used directly rather than OKLCH-interpolated.",
    tokens: {
      "brand-light": "#E7F0FA",
      brand: "#1573D5",
      "brand-dark": "#0051A0",
      "neutral-50": "#FFFFFF",
      "neutral-100": "#F8F9FA",
      "neutral-200": "#E9ECEF",
      "neutral-300": "#DEE2E6",
      "neutral-400": "#CED4DA",
      "neutral-500": "#ADB5BD",
      "neutral-600": "#868E96",
      "neutral-700": "#495057",
      "neutral-800": "#373A3C",
      "neutral-900": "#212529",
      success: "#3FB618",
      "success-strong": "#005F00",
      warning: "#FF7518",
      "warning-strong": "#A41800",
      error: "#FF0039",
      "error-strong": "#A50000",
      info: "#9954BB",
      "info-strong": "#752F94",
    },
  },
  {
    id: "flatly",
    displayName: "Flatly",
    moodFamily: "Light Professional",
    sourceReference:
      "Bootswatch's real, live-fetched flatly/_variables.scss. Same derivation method as Corporate/Forest/Nord/Dracula/Business (feature 017 Phase 4). Neutral scale is Bootstrap's own real gray-100..900. Note: Flatly's own primary ($blue override, #2c3e50) is a desaturated dark navy, not a vivid blue — used verbatim.",
    tokens: {
      "brand-light": "#ABADAF",
      brand: "#2C3E50",
      "brand-dark": "#2A3948",
      "neutral-50": "#FFFFFF",
      "neutral-100": "#F8F9FA",
      "neutral-200": "#ECF0F1",
      "neutral-300": "#DEE2E6",
      "neutral-400": "#CED4DA",
      "neutral-500": "#B4BCC2",
      "neutral-600": "#95A5A6",
      "neutral-700": "#7B8A8B",
      "neutral-800": "#343A40",
      "neutral-900": "#212529",
      success: "#18BC9C",
      "success-strong": "#006045",
      warning: "#F39C12",
      "warning-strong": "#8F3F00",
      error: "#E74C3C",
      "error-strong": "#AE0000",
      info: "#3498DB",
      "info-strong": "#005593",
    },
  },
  {
    id: "litera",
    displayName: "Litera",
    moodFamily: "Light Professional",
    sourceReference:
      "Bootswatch's real, live-fetched litera/_variables.scss. Same derivation method as Corporate/Forest/Nord/Dracula/Business (feature 017 Phase 4). Neutral scale is Bootstrap's own real gray-100..900.",
    tokens: {
      "brand-light": "#E8EFFA",
      brand: "#336FD7",
      "brand-dark": "#1D4DA2",
      "neutral-50": "#FFFFFF",
      "neutral-100": "#F8F9FA",
      "neutral-200": "#E9ECEF",
      "neutral-300": "#DDDDDD",
      "neutral-400": "#CED4DA",
      "neutral-500": "#ADB5BD",
      "neutral-600": "#868E96",
      "neutral-700": "#495057",
      "neutral-800": "#343A40",
      "neutral-900": "#212529",
      success: "#02B875",
      "success-strong": "#006125",
      warning: "#F0AD4E",
      "warning-strong": "#824600",
      error: "#D9534F",
      "error-strong": "#A11A21",
      info: "#17A2B8",
      "info-strong": "#005A6E",
    },
  },
  {
    id: "lumen",
    displayName: "Lumen",
    moodFamily: "Light Professional",
    sourceReference:
      "Bootswatch's real, live-fetched lumen/_variables.scss. Same derivation method as Corporate/Forest/Nord/Dracula/Business (feature 017 Phase 4). Neutral scale is Bootstrap's own real gray-100..900.",
    tokens: {
      "brand-light": "#E1EAEF",
      brand: "#007AA7",
      "brand-dark": "#00567A",
      "neutral-50": "#FFFFFF",
      "neutral-100": "#F6F6F6",
      "neutral-200": "#F0F0F0",
      "neutral-300": "#DEE2E6",
      "neutral-400": "#CED4DA",
      "neutral-500": "#ADB5BD",
      "neutral-600": "#999999",
      "neutral-700": "#555555",
      "neutral-800": "#333333",
      "neutral-900": "#222222",
      success: "#28B62C",
      "success-strong": "#006400",
      warning: "#FF851B",
      "warning-strong": "#9E2A00",
      error: "#FF4136",
      "error-strong": "#AE0000",
      info: "#75CAEB",
      "info-strong": "#005C79",
    },
  },
  {
    id: "zephyr",
    displayName: "Zephyr",
    moodFamily: "Light Professional",
    sourceReference:
      "Bootswatch's real, live-fetched zephyr/_variables.scss. Same derivation method as Corporate/Forest/Nord/Dracula/Business (feature 017 Phase 4). Neutral scale is Bootstrap's own real gray-100..900.",
    tokens: {
      "brand-light": "#DDE4F3",
      brand: "#3459E6",
      "brand-dark": "#2846B9",
      "neutral-50": "#FFFFFF",
      "neutral-100": "#F8F9FA",
      "neutral-200": "#E9ECEF",
      "neutral-300": "#DEE2E6",
      "neutral-400": "#CED4DA",
      "neutral-500": "#ADB5BD",
      "neutral-600": "#6C757D",
      "neutral-700": "#495057",
      "neutral-800": "#343A40",
      "neutral-900": "#212529",
      success: "#2FB380",
      "success-strong": "#006336",
      warning: "#F4BD61",
      "warning-strong": "#7A4900",
      error: "#DA292E",
      "error-strong": "#A70000",
      info: "#287BB5",
      "info-strong": "#00578F",
    },
  },
  {
    id: "silk",
    displayName: "Silk",
    moodFamily: "Light Professional",
    sourceReference:
      "DaisyUI v5's real, live-fetched silk.css. Same derivation method as Corporate/Forest/Nord/Dracula/Business (feature 017 Phase 4). DaisyUI's own primary here is a deliberately near-black, muted tone (premium/soft aesthetic per research.md), not a vivid brand hue — used verbatim; brand-dark nudged further per this catalog's standard AAA-vs-white-text derivation.",
    tokens: {
      "brand-light": "#878788",
      brand: "#1C1C29",
      "brand-dark": "#181822",
      "neutral-50": "#F7F5F3",
      "neutral-100": "#D7D4D2",
      "neutral-200": "#BFBDBA",
      "neutral-300": "#ABA8A5",
      "neutral-400": "#989592",
      "neutral-500": "#878480",
      "neutral-600": "#777370",
      "neutral-700": "#676360",
      "neutral-800": "#595551",
      "neutral-900": "#4B4743",
      success: "#AFD89E",
      "success-strong": "#345824",
      warning: "#EFC375",
      "warning-strong": "#714900",
      error: "#E9575A",
      "error-strong": "#A30121",
      info: "#78C8FF",
      "info-strong": "#005386",
    },
  },
  {
    id: "winter",
    displayName: "Winter",
    moodFamily: "Light Professional",
    sourceReference:
      "DaisyUI v5's real, live-fetched winter.css. Same derivation method as Corporate/Forest/Nord/Dracula/Business (feature 017 Phase 4).",
    tokens: {
      "brand-light": "#E7F2FF",
      brand: "#0069FF",
      "brand-dark": "#0047C9",
      "neutral-50": "#FFFFFF",
      "neutral-100": "#E2DCE0",
      "neutral-200": "#CCC2CB",
      "neutral-300": "#B6ADBA",
      "neutral-400": "#A199AB",
      "neutral-500": "#8C889E",
      "neutral-600": "#777891",
      "neutral-700": "#636984",
      "neutral-800": "#4E5B77",
      "neutral-900": "#394E6A",
      success: "#81CFD1",
      "success-strong": "#006163",
      warning: "#EFD7BC",
      "warning-strong": "#66523A",
      error: "#D17979",
      "error-strong": "#88383B",
      info: "#94E7FB",
      "info-strong": "#005E70",
    },
  },
  {
    id: "cupcake",
    displayName: "Cupcake",
    moodFamily: "Warm/Organic Light",
    sourceReference:
      "DaisyUI v5's real, live-fetched cupcake.css. Same derivation method as Corporate/Forest/Nord/Dracula/Business (feature 017 Phase 4).",
    tokens: {
      "brand-light": "#D5E1DE",
      brand: "#007E6B",
      "brand-dark": "#005849",
      "neutral-50": "#FAF7F5",
      "neutral-100": "#D7CBC7",
      "neutral-200": "#BEAAA8",
      "neutral-300": "#A78E90",
      "neutral-400": "#91757B",
      "neutral-500": "#7B5D6A",
      "neutral-600": "#66485B",
      "neutral-700": "#51354D",
      "neutral-800": "#3D2340",
      "neutral-900": "#291334",
      success: "#00BA7B",
      "success-strong": "#005D26",
      warning: "#EEAF00",
      "warning-strong": "#7B4000",
      error: "#FE1C55",
      "error-strong": "#A4000F",
      info: "#00A4F2",
      "info-strong": "#004D95",
    },
  },
  {
    id: "sandstone",
    displayName: "Sandstone",
    moodFamily: "Warm/Organic Light",
    sourceReference:
      "Bootswatch's real, live-fetched sandstone/_variables.scss. Same derivation method as Corporate/Forest/Nord/Dracula/Business (feature 017 Phase 4). Neutral scale is Bootswatch's own real gray-100..900. Uses $orange (not $yellow) for warning, per its own _variables.scss.",
    tokens: {
      "brand-light": "#CCD1D6",
      brand: "#325D88",
      "brand-dark": "#2E5275",
      "neutral-50": "#FFFFFF",
      "neutral-100": "#F8F9FA",
      "neutral-200": "#F8F5F0",
      "neutral-300": "#DFD7CA",
      "neutral-400": "#CED4DA",
      "neutral-500": "#98978B",
      "neutral-600": "#8E8C84",
      "neutral-700": "#495057",
      "neutral-800": "#3E3F3A",
      "neutral-900": "#212529",
      success: "#93C54B",
      "success-strong": "#325C00",
      warning: "#F47C3C",
      "warning-strong": "#9A2800",
      error: "#D9534F",
      "error-strong": "#A11A21",
      info: "#29ABE0",
      "info-strong": "#005586",
    },
  },
  {
    id: "garden",
    displayName: "Garden",
    moodFamily: "Warm/Organic Light",
    sourceReference:
      "DaisyUI v5's real, live-fetched garden.css. Same derivation method as Corporate/Forest/Nord/Dracula/Business (feature 017 Phase 4).",
    tokens: {
      "brand-light": "#E7CFD3",
      brand: "#C9004D",
      "brand-dark": "#89002B",
      "neutral-50": "#E9E7E7",
      "neutral-100": "#BEBDBD",
      "neutral-200": "#A09E9E",
      "neutral-300": "#858484",
      "neutral-400": "#6D6C6C",
      "neutral-500": "#575656",
      "neutral-600": "#434242",
      "neutral-700": "#302F2F",
      "neutral-800": "#1F1F1F",
      "neutral-900": "#100F0F",
      success: "#00A96E",
      "success-strong": "#005420",
      warning: "#FFBE00",
      "warning-strong": "#7A3400",
      error: "#F43949",
      "error-strong": "#950000",
      info: "#00B5FF",
      "info-strong": "#00438D",
    },
  },
  {
    id: "autumn",
    displayName: "Autumn",
    moodFamily: "Warm/Organic Light",
    sourceReference:
      "DaisyUI v5's real, live-fetched autumn.css. Same derivation method as Corporate/Forest/Nord/Dracula/Business (feature 017 Phase 4).",
    tokens: {
      "brand-light": "#C7B9B9",
      brand: "#8C0327",
      "brand-dark": "#7D1528",
      "neutral-50": "#F1F1F1",
      "neutral-100": "#C6C6C6",
      "neutral-200": "#A7A7A7",
      "neutral-300": "#8C8C8C",
      "neutral-400": "#747474",
      "neutral-500": "#5D5D5D",
      "neutral-600": "#494949",
      "neutral-700": "#363636",
      "neutral-800": "#242424",
      "neutral-900": "#141414",
      success: "#499380",
      "success-strong": "#005847",
      warning: "#E97F17",
      "warning-strong": "#8A2700",
      error: "#D40014",
      "error-strong": "#990000",
      info: "#44ADBB",
      "info-strong": "#005360",
    },
  },
  {
    id: "lemonade",
    displayName: "Lemonade",
    moodFamily: "Warm/Organic Light",
    sourceReference:
      "DaisyUI v5's real, live-fetched lemonade.css. Same derivation method as Corporate/Forest/Nord/Dracula/Business (feature 017 Phase 4).",
    tokens: {
      "brand-light": "#DFE7DA",
      brand: "#2E8100",
      "brand-dark": "#165B00",
      "neutral-50": "#F8FDEF",
      "neutral-100": "#CBD0C4",
      "neutral-200": "#ACB0A5",
      "neutral-300": "#90938B",
      "neutral-400": "#777A72",
      "neutral-500": "#60625C",
      "neutral-600": "#4B4D48",
      "neutral-700": "#373935",
      "neutral-800": "#252624",
      "neutral-900": "#151614",
      success: "#B9DCC6",
      "success-strong": "#3D5B49",
      warning: "#D7D3B0",
      "warning-strong": "#585435",
      error: "#AE8884",
      "error-strong": "#6B4945",
      info: "#B1D9E9",
      "info-strong": "#355966",
    },
  },
  {
    id: "caramellatte",
    displayName: "Caramellatte",
    moodFamily: "Warm/Organic Light",
    sourceReference:
      "DaisyUI v5's real, live-fetched caramellatte.css. Same derivation method as Corporate/Forest/Nord/Dracula/Business (feature 017 Phase 4). DaisyUI's own primary here is literal black (oklch(0% 0 0)) — used verbatim, matching its premium/restrained aesthetic per research.md.",
    tokens: {
      "brand-light": "#454545",
      brand: "#000000",
      "brand-dark": "#000000",
      "neutral-50": "#FFF7ED",
      "neutral-100": "#E7D4C0",
      "neutral-200": "#D7BAA0",
      "neutral-300": "#C8A285",
      "neutral-400": "#BA8C6C",
      "neutral-500": "#AE7756",
      "neutral-600": "#A16342",
      "neutral-700": "#954F2F",
      "neutral-800": "#883C1D",
      "neutral-900": "#7C2808",
      success: "#006044",
      "success-strong": "#005A3F",
      warning: "#FCB700",
      "warning-strong": "#814000",
      error: "#F0555A",
      "error-strong": "#A2001A",
      info: "#193AB7",
      "info-strong": "#1433B0",
    },
  },
  {
    id: "everforest",
    displayName: "Everforest",
    moodFamily: "Nature/Earth",
    sourceReference:
      "The Everforest project's own real, published palette (github.com/sainnhe/everforest palette.md) — \"medium\" dark background tier, default foreground/accent set.",
    tokens: {
      "brand-light": "#42443F",
      brand: "#A7C080",
      "brand-dark": "#4C5E2C",
      "neutral-50": "#232A2E",
      "neutral-100": "#374446",
      "neutral-200": "#475856",
      "neutral-300": "#586A64",
      "neutral-400": "#6A7C70",
      "neutral-500": "#7E8C7B",
      "neutral-600": "#929C86",
      "neutral-700": "#A7AA91",
      "neutral-800": "#BDB89D",
      "neutral-900": "#D3C6AA",
      success: "#A7C080",
      "success-strong": "#B3CD8C",
      warning: "#DBBC7F",
      "warning-strong": "#E2C285",
      error: "#E67E80",
      "error-strong": "#FFA4A5",
      info: "#7FBBB3",
      "info-strong": "#8BC8C0",
    },
  },
  {
    id: "gruvbox",
    displayName: "Gruvbox",
    moodFamily: "Nature/Earth",
    sourceReference:
      "The Gruvbox project's own real, published palette (github.com/morhetz/gruvbox gruvbox_256palette.sh) — the well-known, widely-referenced hex values (bg0 #282828, fg1 #ebdbb2, bright green/yellow/red/blue accents).",
    tokens: {
      "brand-light": "#414238",
      brand: "#B8BB26",
      "brand-dark": "#595900",
      "neutral-50": "#282828",
      "neutral-100": "#45433D",
      "neutral-200": "#5C584E",
      "neutral-300": "#726C5E",
      "neutral-400": "#87806C",
      "neutral-500": "#9B927B",
      "neutral-600": "#B0A589",
      "neutral-700": "#C4B797",
      "neutral-800": "#D7C9A4",
      "neutral-900": "#EBDBB2",
      success: "#B8BB26",
      "success-strong": "#C5C839",
      warning: "#FABD2F",
      "warning-strong": "#FFC439",
      error: "#FB4934",
      "error-strong": "#FFA488",
      info: "#83A598",
      "info-strong": "#A2C5B7",
    },
  },
  {
    id: "aqua",
    displayName: "Aqua",
    moodFamily: "Nature/Earth",
    sourceReference:
      "DaisyUI v5's real, live-fetched aqua.css.",
    tokens: {
      "brand-light": "#515C5D",
      brand: "#13ECF3",
      "brand-dark": "#005E65",
      "neutral-50": "#1A368B",
      "neutral-100": "#2856A0",
      "neutral-200": "#376CAF",
      "neutral-300": "#4881BC",
      "neutral-400": "#5A93C8",
      "neutral-500": "#6CA5D4",
      "neutral-600": "#7EB6DE",
      "neutral-700": "#91C7E9",
      "neutral-800": "#A4D6F4",
      "neutral-900": "#B8E6FE",
      success: "#18A34A",
      "success-strong": "#79F294",
      warning: "#D97708",
      "warning-strong": "#FFCB75",
      error: "#FF7265",
      "error-strong": "#FFC2B0",
      info: "#2563EB",
      "info-strong": "#98E1FF",
    },
  },
  {
    id: "emerald",
    displayName: "Emerald",
    moodFamily: "Nature/Earth",
    sourceReference:
      "DaisyUI v5's real, live-fetched emerald.css.",
    tokens: {
      "brand-light": "#E4EDE6",
      brand: "#0F8649",
      "brand-dark": "#00602F",
      "neutral-50": "#FFFFFF",
      "neutral-100": "#DDD9DB",
      "neutral-200": "#C4BEC3",
      "neutral-300": "#ACA6AE",
      "neutral-400": "#96909B",
      "neutral-500": "#817D8A",
      "neutral-600": "#6C6B7A",
      "neutral-700": "#585A6A",
      "neutral-800": "#454B5B",
      "neutral-900": "#333C4D",
      success: "#00A96E",
      "success-strong": "#00602B",
      warning: "#FFBE00",
      "warning-strong": "#864000",
      error: "#FF5861",
      "error-strong": "#AB0007",
      info: "#00B5FF",
      "info-strong": "#0056A1",
    },
  },
  {
    id: "slate",
    displayName: "Slate",
    moodFamily: "Cool/Tech Minimal",
    sourceReference:
      "Bootswatch's real, live-fetched slate/_variables.scss — a dark theme (body-bg overrides to gray-900 #272B30). Its own real primary IS a gray ($gray-800), a deliberate monochrome accent matching research.md's \"cool blue-gray dark\" description — used verbatim.",
    tokens: {
      "brand-light": "#272828",
      brand: "#8F949A",
      "brand-dark": "#505459",
      "neutral-50": "#272B30",
      "neutral-100": "#3A3F42",
      "neutral-200": "#494F50",
      "neutral-300": "#585D5C",
      "neutral-400": "#676B69",
      "neutral-500": "#757876",
      "neutral-600": "#838483",
      "neutral-700": "#919190",
      "neutral-800": "#9E9E9D",
      "neutral-900": "#AAAAAA",
      success: "#62C462",
      "success-strong": "#76D875",
      warning: "#F89406",
      "warning-strong": "#FFAE3A",
      error: "#EE5F5B",
      "error-strong": "#FFA79E",
      info: "#5BC0DE",
      "info-strong": "#69CDEB",
    },
  },
  {
    id: "spacelab",
    displayName: "Spacelab",
    moodFamily: "Cool/Tech Minimal",
    sourceReference:
      "Bootswatch's real, live-fetched spacelab/_variables.scss.",
    tokens: {
      "brand-light": "#E0E4E9",
      brand: "#446E9B",
      "brand-dark": "#35577C",
      "neutral-50": "#FFFFFF",
      "neutral-100": "#F8F9FA",
      "neutral-200": "#EEEEEE",
      "neutral-300": "#DEE2E6",
      "neutral-400": "#CED4DA",
      "neutral-500": "#999999",
      "neutral-600": "#777777",
      "neutral-700": "#495057",
      "neutral-800": "#333333",
      "neutral-900": "#2D2D2D",
      success: "#3CB521",
      "success-strong": "#006400",
      warning: "#D47500",
      "warning-strong": "#913800",
      error: "#CD0200",
      "error-strong": "#A90000",
      info: "#3399F3",
      "info-strong": "#004FA3",
    },
  },
  {
    id: "cerulean",
    displayName: "Cerulean",
    moodFamily: "Cool/Tech Minimal",
    sourceReference:
      "Bootswatch's real, live-fetched cerulean/_variables.scss. Note: Cerulean's own primary is $cyan (not $blue) per its own _variables.scss.",
    tokens: {
      "brand-light": "#E2EBF2",
      brand: "#0078B8",
      "brand-dark": "#005588",
      "neutral-50": "#FFFFFF",
      "neutral-100": "#F8F9FA",
      "neutral-200": "#E9ECEF",
      "neutral-300": "#DEE2E6",
      "neutral-400": "#CED4DA",
      "neutral-500": "#ADB5BD",
      "neutral-600": "#868E96",
      "neutral-700": "#495057",
      "neutral-800": "#343A40",
      "neutral-900": "#212529",
      success: "#73A839",
      "success-strong": "#2F5F00",
      warning: "#DD5600",
      "warning-strong": "#A51C00",
      error: "#C71C22",
      "error-strong": "#AA0000",
      info: "#033C73",
      "info-strong": "#00366D",
    },
  },
  {
    id: "quartz",
    displayName: "Quartz",
    moodFamily: "Cool/Tech Minimal",
    sourceReference:
      "Bootswatch's real, live-fetched quartz/_variables.scss — a genuine outlier: its own real body-bg overrides to a colorful purple ($purple, #686DC3, L=57%), not white, and its own primary is $pink (not $blue). KNOWN LIMITATION found during derivation: #686DC3's own relative luminance caps the maximum possible contrast against literal black at ~4.56:1 — barely clears this catalog's 4.5:1 Button-focus-outline bar, and the OKLCH engine's L=0-with-nonzero-chroma out-of-gamut clipping (not exactly pure black) lands just under it (4.45:1), tracked in scripts/check-contrast.mjs's KNOWN_THEME_CONTRAST_GAPS.",
    tokens: {
      "brand-light": "#4F3E40",
      brand: "#120000",
      "brand-dark": "#0F0000",
      "neutral-50": "#686DC3",
      "neutral-100": "#A07BC0",
      "neutral-200": "#BF89B9",
      "neutral-300": "#D49AB5",
      "neutral-400": "#E1ACB4",
      "neutral-500": "#E9BFBA",
      "neutral-600": "#EED1C5",
      "neutral-700": "#F2E2D6",
      "neutral-800": "#F7F1EA",
      "neutral-900": "#FFFFFF",
      success: "#41D7A7",
      "success-strong": "#000000",
      warning: "#FFC107",
      "warning-strong": "#000800",
      error: "#5F0000",
      "error-strong": "#080200",
      info: "#39CBFB",
      "info-strong": "#010012",
    },
  },
  {
    id: "journal",
    displayName: "Journal",
    moodFamily: "Cool/Tech Minimal",
    sourceReference:
      "Bootswatch's real, live-fetched journal/_variables.scss. Note: Journal's own primary is $blue, itself overridden to a salmon-red (#eb6864, not literally blue) per its own _variables.scss — used verbatim.",
    tokens: {
      "brand-light": "#FFF0EF",
      brand: "#C84847",
      "brand-dark": "#952E2E",
      "neutral-50": "#FFFFFF",
      "neutral-100": "#F8F9FA",
      "neutral-200": "#EEEEEE",
      "neutral-300": "#DEE2E6",
      "neutral-400": "#CED4DA",
      "neutral-500": "#AAAAAA",
      "neutral-600": "#777777",
      "neutral-700": "#495057",
      "neutral-800": "#333333",
      "neutral-900": "#222222",
      success: "#22B24C",
      "success-strong": "#006100",
      warning: "#F5E625",
      "warning-strong": "#685500",
      error: "#E76D00",
      "error-strong": "#9B2400",
      info: "#336699",
      "info-strong": "#215586",
    },
  },
  {
    id: "dim",
    displayName: "Dim",
    moodFamily: "Dark Moody/Professional",
    sourceReference:
      "DaisyUI v5's real, live-fetched dim.css.",
    tokens: {
      "brand-light": "#575D56",
      brand: "#9FE88D",
      "brand-dark": "#296219",
      "neutral-50": "#2A303C",
      "neutral-100": "#3F4855",
      "neutral-200": "#4F5B68",
      "neutral-300": "#5E6C79",
      "neutral-400": "#6D7D8A",
      "neutral-500": "#7B8D9A",
      "neutral-600": "#899DA9",
      "neutral-700": "#97ADB8",
      "neutral-800": "#A5BDC7",
      "neutral-900": "#B2CCD6",
      success: "#62EFBD",
      "success-strong": "#6AF6C3",
      warning: "#EFD057",
      "warning-strong": "#F6D75E",
      error: "#FFAE9B",
      "error-strong": "#FFB5A1",
      info: "#28EBFF",
      "info-strong": "#36F2FF",
    },
  },
  {
    id: "night",
    displayName: "Night",
    moodFamily: "Dark Moody/Professional",
    sourceReference:
      "DaisyUI v5's real, live-fetched night.css.",
    tokens: {
      "brand-light": "#373F44",
      brand: "#3ABDF8",
      "brand-dark": "#005986",
      "neutral-50": "#0F172A",
      "neutral-100": "#2A3243",
      "neutral-200": "#404757",
      "neutral-300": "#545B6A",
      "neutral-400": "#686E7C",
      "neutral-500": "#7C818D",
      "neutral-600": "#8F949E",
      "neutral-700": "#A3A6AF",
      "neutral-800": "#B6B9BF",
      "neutral-900": "#C9CBD0",
      success: "#2ED4BF",
      "success-strong": "#39DBC5",
      warning: "#F4BF51",
      "warning-strong": "#FBC658",
      error: "#FB7085",
      "error-strong": "#FF8397",
      info: "#0CA5E9",
      "info-strong": "#29B2F7",
    },
  },
  {
    id: "darkly",
    displayName: "Darkly",
    moodFamily: "Dark Moody/Professional",
    sourceReference:
      "Bootswatch's real, live-fetched darkly/_variables.scss — a dark theme (body-bg overrides to gray-900 #222222).",
    tokens: {
      "brand-light": "#1F2125",
      brand: "#6A8FB7",
      "brand-dark": "#3D5A79",
      "neutral-50": "#222222",
      "neutral-100": "#424242",
      "neutral-200": "#5C5C5C",
      "neutral-300": "#757575",
      "neutral-400": "#8D8D8D",
      "neutral-500": "#A4A4A4",
      "neutral-600": "#BBBBBB",
      "neutral-700": "#D2D2D2",
      "neutral-800": "#E9E9E9",
      "neutral-900": "#FFFFFF",
      success: "#00BC8C",
      "success-strong": "#33D09E",
      warning: "#F39C12",
      "warning-strong": "#FAA221",
      error: "#E74C3C",
      "error-strong": "#FF9680",
      info: "#3498DB",
      "info-strong": "#5EBEFF",
    },
  },
  {
    id: "cyborg",
    displayName: "Cyborg",
    moodFamily: "Dark Moody/Professional",
    sourceReference:
      "Bootswatch's real, live-fetched cyborg/_variables.scss — a dark theme (body-bg overrides to a literal near-black #060606). Note: Cyborg's own $cyan is actually a purple (#9933cc, its own 3-digit hex #93c) per its own _variables.scss — used verbatim.",
    tokens: {
      "brand-light": "#22292D",
      brand: "#2A9FD6",
      "brand-dark": "#005C86",
      "neutral-50": "#060606",
      "neutral-100": "#1D1D1D",
      "neutral-200": "#313130",
      "neutral-300": "#434343",
      "neutral-400": "#555655",
      "neutral-500": "#676867",
      "neutral-600": "#797A79",
      "neutral-700": "#8A8C8B",
      "neutral-800": "#9C9D9C",
      "neutral-900": "#ADAFAE",
      success: "#77B300",
      "success-strong": "#7DB915",
      warning: "#FF8800",
      "warning-strong": "#FF8E16",
      error: "#CC0000",
      "error-strong": "#FF6956",
      info: "#9933CC",
      "info-strong": "#D371FF",
    },
  },
  {
    id: "superhero",
    displayName: "Superhero",
    moodFamily: "Dark Moody/Professional",
    sourceReference:
      "Bootswatch's real, live-fetched superhero/_variables.scss — a dark theme (body-bg overrides to a dark navy #0F2537), matching research.md's \"dark navy with red accent\" description.",
    tokens: {
      "brand-light": "#2C221E",
      brand: "#DF6919",
      "brand-dark": "#983A00",
      "neutral-50": "#0F2537",
      "neutral-100": "#2A464E",
      "neutral-200": "#445E5F",
      "neutral-300": "#5F746F",
      "neutral-400": "#798881",
      "neutral-500": "#939C94",
      "neutral-600": "#ABB0A8",
      "neutral-700": "#C2C3BE",
      "neutral-800": "#D7D7D4",
      "neutral-900": "#EBEBEB",
      success: "#5CB85C",
      "success-strong": "#6FCB6F",
      warning: "#FFC107",
      "warning-strong": "#FFC81E",
      error: "#D9534F",
      "error-strong": "#FF938B",
      info: "#5BC0DE",
      "info-strong": "#62C6E5",
    },
  },
  {
    id: "abyss",
    displayName: "Abyss",
    moodFamily: "Dark Moody/Professional",
    sourceReference:
      "DaisyUI v5's real, live-fetched abyss.css. Its own real primary is a highly saturated near-fluorescent green (oklch(92% 0.2653 125)) — used verbatim, a deliberate DaisyUI design choice for this theme.",
    tokens: {
      "brand-light": "#686F5E",
      brand: "#BDFF00",
      "brand-dark": "#376200",
      "neutral-50": "#001E29",
      "neutral-100": "#003F38",
      "neutral-200": "#0C5842",
      "neutral-300": "#3C6D4A",
      "neutral-400": "#618153",
      "neutral-500": "#83935E",
      "neutral-600": "#A4A56C",
      "neutral-700": "#C3B57C",
      "neutral-800": "#E2C690",
      "neutral-900": "#FFD6A7",
      success: "#01DF72",
      "success-strong": "#1DE578",
      warning: "#FFBF00",
      "warning-strong": "#FFC600",
      error: "#F04E4F",
      "error-strong": "#FF847F",
      info: "#00BAFE",
      "info-strong": "#00C0FF",
    },
  },
  {
    id: "synthwave",
    displayName: "Synthwave",
    moodFamily: "Dark Vibrant/Expressive",
    sourceReference:
      "DaisyUI v5's real, live-fetched synthwave.css.",
    tokens: {
      "brand-light": "#3B2F34",
      brand: "#F861B4",
      "brand-dark": "#9B1F68",
      "neutral-50": "#09002F",
      "neutral-100": "#1D1A4F",
      "neutral-200": "#2F2F68",
      "neutral-300": "#404380",
      "neutral-400": "#505696",
      "neutral-500": "#6169AC",
      "neutral-600": "#717BC2",
      "neutral-700": "#818DD7",
      "neutral-800": "#919FEC",
      "neutral-900": "#A1B1FF",
      success: "#00D3BB",
      "success-strong": "#00D9C2",
      warning: "#FEDE1C",
      "warning-strong": "#FFE42B",
      error: "#EC8C78",
      "error-strong": "#F3927E",
      info: "#00BAFE",
      "info-strong": "#00C0FF",
    },
  },
  {
    id: "cyberpunk",
    displayName: "Cyberpunk",
    moodFamily: "Dark Vibrant/Expressive",
    sourceReference:
      "DaisyUI v5's real, live-fetched cyberpunk.css. KNOWN FINDING (verified empirically, not assumed from the name): despite \"Cyberpunk\" evoking a dark neon aesthetic, DaisyUI's own theme explicitly declares color-scheme: light — its base-100 is a vivid neon yellow (oklch(94.51% 0.179 104.32)), not a dark surface. Kept in the Dark Vibrant/Expressive mood family per research.md's aesthetic categorization (the neon-punk DIRECTION, not literal light/dark rendering mode) — used verbatim, real value.",
    tokens: {
      "brand-light": "#F6E3E6",
      brand: "#C9145C",
      "brand-dark": "#94003E",
      "neutral-50": "#FFF248",
      "neutral-100": "#E2B02D",
      "neutral-200": "#C1852A",
      "neutral-300": "#9E622A",
      "neutral-400": "#7B4627",
      "neutral-500": "#592E20",
      "neutral-600": "#391A16",
      "neutral-700": "#1C0A0A",
      "neutral-800": "#050102",
      "neutral-900": "#000000",
      success: "#00A96E",
      "success-strong": "#005420",
      warning: "#FFBE00",
      "warning-strong": "#803A00",
      error: "#F43949",
      "error-strong": "#950000",
      info: "#00B5FF",
      "info-strong": "#004A94",
    },
  },
  {
    id: "tokyonight",
    displayName: "Tokyo Night",
    moodFamily: "Dark Vibrant/Expressive",
    sourceReference:
      "The Tokyo Night project's own real, published VS Code theme JSON (github.com/enkia/tokyo-night-vscode-theme themes/tokyo-night-color-theme.json) — editor.background/foreground as base/ink, terminal ANSI blue (#7aa2f7, the palette's own iconic accent) as brand primary, ANSI red/yellow/green plus editorInfo.foreground for the remaining semantic roles.",
    tokens: {
      "brand-light": "#32353C",
      brand: "#7AA2F7",
      "brand-dark": "#375596",
      "neutral-50": "#1A1B26",
      "neutral-100": "#333545",
      "neutral-200": "#47495D",
      "neutral-300": "#595D74",
      "neutral-400": "#6B708B",
      "neutral-500": "#7D82A0",
      "neutral-600": "#8E94B6",
      "neutral-700": "#9FA6CB",
      "neutral-800": "#AFB8E0",
      "neutral-900": "#C0CAF5",
      success: "#73DACA",
      "success-strong": "#7AE1D0",
      warning: "#E0AF68",
      "warning-strong": "#E7B56E",
      error: "#F7768E",
      "error-strong": "#FF89A0",
      info: "#0DA0BA",
      "info-strong": "#44C0DA",
    },
  },
  {
    id: "halloween",
    displayName: "Halloween",
    moodFamily: "Dark Vibrant/Expressive",
    sourceReference:
      "DaisyUI v5's real, live-fetched halloween.css.",
    tokens: {
      "brand-light": "#4C4139",
      brand: "#FF8F00",
      "brand-dark": "#9D3800",
      "neutral-50": "#1B1816",
      "neutral-100": "#353231",
      "neutral-200": "#4A4746",
      "neutral-300": "#5E5C5B",
      "neutral-400": "#716F6F",
      "neutral-500": "#848282",
      "neutral-600": "#979595",
      "neutral-700": "#A9A8A8",
      "neutral-800": "#BBBBBB",
      "neutral-900": "#CDCDCD",
      success: "#18A34A",
      "success-strong": "#47C369",
      warning: "#D97708",
      "warning-strong": "#F49035",
      error: "#F35248",
      "error-strong": "#FF8879",
      info: "#2563EB",
      "info-strong": "#66ABFF",
    },
  },
  {
    id: "luxury",
    displayName: "Luxury",
    moodFamily: "Dark Vibrant/Expressive",
    sourceReference:
      "DaisyUI v5's real, live-fetched luxury.css. Its own real primary is literal white (oklch(100% 0 0)) — used verbatim, matching its dark-gold/black premium aesthetic per research.md.",
    tokens: {
      "brand-light": "#838383",
      brand: "#FFFFFF",
      "brand-dark": "#585858",
      "neutral-50": "#09090B",
      "neutral-100": "#251E2A",
      "neutral-200": "#402D3E",
      "neutral-300": "#5C3B4C",
      "neutral-400": "#784954",
      "neutral-500": "#935857",
      "neutral-600": "#AB6857",
      "neutral-700": "#BF7A54",
      "neutral-800": "#D08F50",
      "neutral-900": "#DCA54D",
      success: "#87D03A",
      "success-strong": "#8DD742",
      warning: "#E2D563",
      "warning-strong": "#E8DC69",
      error: "#FF6F6F",
      "error-strong": "#FF7675",
      info: "#67C6FF",
      "info-strong": "#6DCCFF",
    },
  },
  {
    id: "retro",
    displayName: "Retro",
    moodFamily: "Distinctive/Characterful",
    sourceReference:
      "DaisyUI v5's real, live-fetched retro.css.",
    tokens: {
      "brand-light": "#E9DEDE",
      brand: "#A04A4E",
      "brand-dark": "#732E32",
      "neutral-50": "#ECE3CA",
      "neutral-100": "#D6C5A5",
      "neutral-200": "#C7AE8A",
      "neutral-300": "#BA9A72",
      "neutral-400": "#AF875D",
      "neutral-500": "#A4754A",
      "neutral-600": "#996439",
      "neutral-700": "#8E5328",
      "neutral-800": "#844217",
      "neutral-900": "#793205",
      success: "#00776F",
      "success-strong": "#004942",
      warning: "#F34700",
      "warning-strong": "#8E0000",
      error: "#E2474E",
      "error-strong": "#8D0005",
      info: "#0082CE",
      "info-strong": "#003F87",
    },
  },
  {
    id: "coffee",
    displayName: "Coffee",
    moodFamily: "Distinctive/Characterful",
    sourceReference:
      "DaisyUI v5's real, live-fetched coffee.css.",
    tokens: {
      "brand-light": "#3A342F",
      brand: "#DB924C",
      "brand-dark": "#804801",
      "neutral-50": "#261B25",
      "neutral-100": "#412C37",
      "neutral-200": "#583A42",
      "neutral-300": "#6C4749",
      "neutral-400": "#80544F",
      "neutral-500": "#916253",
      "neutral-600": "#A17056",
      "neutral-700": "#AF7F59",
      "neutral-800": "#BB8F5C",
      "neutral-900": "#C59F61",
      success: "#9DB787",
      "success-strong": "#A3BD8D",
      warning: "#FFD260",
      "warning-strong": "#FFD967",
      error: "#FC9581",
      "error-strong": "#FF9B87",
      info: "#8ECAC1",
      "info-strong": "#94D0C7",
    },
  },
  {
    id: "rosepine",
    displayName: "Rose Pine",
    moodFamily: "Distinctive/Characterful",
    sourceReference:
      "The Rosé Pine project's own real, published palette (github.com/rose-pine/palette dist/css/rose-pine.css) — \"main\" (dark) variant. Uses \"iris\" (#c4a7e7, the palette's own flagship accent) as brand primary and \"pine\" (#31748f, the closest natural-toned color in this deliberately muted, green-avoiding palette) for success, per the project's own documented color roles.",
    tokens: {
      "brand-light": "#454348",
      brand: "#C4A7E7",
      "brand-dark": "#614B7B",
      "neutral-50": "#191724",
      "neutral-100": "#363443",
      "neutral-200": "#4D4B5C",
      "neutral-300": "#636173",
      "neutral-400": "#797789",
      "neutral-500": "#8E8C9F",
      "neutral-600": "#A3A1B5",
      "neutral-700": "#B7B5CA",
      "neutral-800": "#CCCADF",
      "neutral-900": "#E0DEF4",
      success: "#31748F",
      "success-strong": "#6FB1CE",
      warning: "#F6C177",
      "warning-strong": "#FDC77D",
      error: "#EB6F92",
      "error-strong": "#FF82A4",
      info: "#9CCFD8",
      "info-strong": "#A2D6DF",
    },
  },
  {
    id: "catppuccin",
    displayName: "Catppuccin",
    moodFamily: "Distinctive/Characterful",
    sourceReference:
      "The Catppuccin project's own real, published palette (github.com/catppuccin/palette palette.json) — \"Mocha\" flavor, the most widely-adopted of its 4 official variants (research.md R3's note: represented as one curated entry, not all 4). Uses \"mauve\" (#cba6f7, Catppuccin's own signature accent) as brand primary.",
    tokens: {
      "brand-light": "#48454C",
      brand: "#CBA6F7",
      "brand-dark": "#674A87",
      "neutral-50": "#1E1E2E",
      "neutral-100": "#38394C",
      "neutral-200": "#4D4F64",
      "neutral-300": "#60637A",
      "neutral-400": "#73778F",
      "neutral-500": "#868BA4",
      "neutral-600": "#989EB8",
      "neutral-700": "#AAB1CC",
      "neutral-800": "#BBC3E0",
      "neutral-900": "#CDD6F4",
      success: "#A6E3A1",
      "success-strong": "#ACEAA7",
      warning: "#F9E2AF",
      "warning-strong": "#FFE9B5",
      error: "#F38BA8",
      "error-strong": "#FA91AE",
      info: "#89B4FA",
      "info-strong": "#8FBAFF",
    },
  },
  // Feature 027 — Claude-Design-inspired batch 2. Each theme's brand/
  // neutral anchors are real values independently derived via a
  // browser-rendered design-language analysis (research.md R2-R3,
  // contracts/source-token-mapping.contract.md); the company each
  // theme drew mood direction from is recorded only in this feature's
  // own research notes, never in shipped code (spec.md's resolved
  // naming decision — generic names only). neutral-100..800 ramps are
  // OKLCH-interpolated between the two real endpoint anchors via a
  // real browser engine (Chromium canvas 2D pixel readback, feature
  // 017's eased t^0.8 method) — not hand-approximated. Semantic
  // success/warning/error/info pairs reuse this catalog's existing
  // default hues wherever the source didn't document a distinct real
  // anchor of its own (research.md R5).
  {
    id: "aurora",
    displayName: "Aurora",
    moodFamily: "Distinctive/Characterful",
    sourceReference:
      "Independently derived light palette — gradient-mesh, editorial-elegance mood family. Real anchors: brand/brand-dark/brand-light from a signature indigo CTA system (primary/press/subdued-hover tiers); neutral-50/900 from the source's own canvas/ink pairing; neutral-100-800 OKLCH-interpolated between them. Semantic hues reused from this catalog's default theme (source documented no distinct semantic palette). See specs/027-claude-design-inspired-themes/research.md R3 for the full derivation record.",
    tokens: {
      "brand-light": "#B9B9F9",
      brand: "#533AFD",
      "brand-dark": "#2E2B8C",
      "neutral-50": "#FFFFFF",
      "neutral-100": "#E3E6E9",
      "neutral-200": "#BCC3CB",
      "neutral-300": "#AAB3BD",
      "neutral-400": "#7F8C9B",
      "neutral-500": "#657586",
      "neutral-600": "#404F5F",
      "neutral-700": "#364A5F",
      "neutral-800": "#21374E",
      "neutral-900": "#0D253D",
      success: "#10B981",
      "success-strong": "#065F46",
      warning: "#F59E0B",
      "warning-strong": "#78350F",
      error: "#EF4444",
      "error-strong": "#991B1B",
      info: "#3B82F6",
      "info-strong": "#1E40AF",
    },
  },
  {
    id: "obsidian",
    displayName: "Obsidian",
    moodFamily: "Dark Moody/Professional",
    sourceReference:
      "Independently derived dark palette — near-black canvas, single restrained lavender-blue accent, ultra-minimal mood family. Real anchors: brand-light from a signature primary-hover tier; neutral-50/900 from the source's own near-black canvas and light-gray ink; neutral-100-800 OKLCH-interpolated, anchored against 2 real intermediate surface-ladder stops. brand-dark is OKLCH-darkened from the real primary anchor (not the source's own barely-darker focus-tint, which reads too close to `brand` for a 7:1 white-on-fill button) — the same \"dark theme needs its own darker press tier\" adjustment feature 017 already made for forest/dracula's brand-dark. success/success-strong use the source's own real documented status-green anchor, OKLCH-lightened for the -strong (ink-on-page) role rather than darkened — matching forest/dracula's own inverted-lightness convention for dark-theme semantic *-strong tokens (a token used both as ink-on-page text AND as Indicator's solid-fill-behind-white-text can't satisfy both roles; the ink-on-page role wins, same trade-off forest/dracula already document). warning/error/info reused from this catalog's default theme (source documented no distinct anchors for those). See specs/027-claude-design-inspired-themes/research.md R3 for the full derivation record.",
    tokens: {
      "brand-light": "#828FFF",
      brand: "#5E6AD2",
      "brand-dark": "#252B5C",
      "neutral-50": "#010102",
      "neutral-100": "#110D0E",
      "neutral-200": "#302C2D",
      "neutral-300": "#4D494A",
      "neutral-400": "#6A6768",
      "neutral-500": "#878485",
      "neutral-600": "#A3A1A2",
      "neutral-700": "#C0BEBE",
      "neutral-800": "#DCDBDB",
      "neutral-900": "#F7F8F8",
      success: "#27A644",
      "success-strong": "#95CF99",
      warning: "#FFBE00",
      "warning-strong": "#FFC500",
      error: "#FF5861",
      "error-strong": "#FF8286",
      info: "#00B5FF",
      "info-strong": "#00BCFF",
    },
  },
  {
    id: "linen",
    displayName: "Linen",
    moodFamily: "Warm/Organic Light",
    sourceReference:
      "Independently derived light palette — warm off-white paper canvas, single confident blue accent, warm-minimalism mood family. Real anchors: brand/brand-dark from a signature blue primary/press pair; brand-light OKLCH-lightened toward white (source's own accent palette is explicitly decorative-only, not a valid pale-brand source — research.md R5); neutral-50/900 from the source's own warm-paper canvas and near-black ink; neutral-100-800 OKLCH-interpolated, anchored against 2 real intermediate ink-tier stops. Semantic hues reused from this catalog's default theme (source documented no distinct semantic palette). See specs/027-claude-design-inspired-themes/research.md R3 for the full derivation record.",
    tokens: {
      "brand-light": "#CEE2FB",
      brand: "#0075DE",
      "brand-dark": "#005199",
      "neutral-50": "#F6F5F4",
      "neutral-100": "#D5D4D4",
      "neutral-200": "#A8A7A7",
      "neutral-300": "#828282",
      "neutral-400": "#626161",
      "neutral-500": "#444444",
      "neutral-600": "#2A2A2A",
      "neutral-700": "#131313",
      "neutral-800": "#030303",
      "neutral-900": "#000000",
      success: "#10B981",
      "success-strong": "#065F46",
      warning: "#F59E0B",
      "warning-strong": "#78350F",
      error: "#EF4444",
      "error-strong": "#991B1B",
      info: "#3B82F6",
      "info-strong": "#1E40AF",
    },
  },
  {
    id: "graphite",
    displayName: "Graphite",
    moodFamily: "Cool/Tech Minimal",
    sourceReference:
      "Independently derived light palette — monochrome ink-on-white precision, developer-platform mood family. Real anchors: brand/brand-dark/brand-light from a signature link/accent blue primary/deep/soft triad (the source's true structural color is ink, already carried by neutral-900); neutral-50/900 from the source's own near-white canvas and near-black ink; neutral-100-800 OKLCH-interpolated, anchored against 3 real intermediate text-ladder stops. error/error-strong and warning/warning-strong use the source's own real documented semantic anchors (darkened via the same OKLCH method for the -strong tiers); success/info reused from this catalog's default theme (source documented no distinct green/blue-info anchors of its own). See specs/027-claude-design-inspired-themes/research.md R3 for the full derivation record.",
    tokens: {
      "brand-light": "#D3E5FF",
      brand: "#0070F3",
      "brand-dark": "#04469B",
      "neutral-50": "#FAFAFA",
      "neutral-100": "#DFDFDF",
      "neutral-200": "#BABABA",
      "neutral-300": "#A5A5A5",
      "neutral-400": "#808080",
      "neutral-500": "#686868",
      "neutral-600": "#515151",
      "neutral-700": "#3C3C3C",
      "neutral-800": "#292929",
      "neutral-900": "#171717",
      success: "#10B981",
      "success-strong": "#065F46",
      warning: "#F5A623",
      "warning-strong": "#513405",
      error: "#EE0000",
      "error-strong": "#770000",
      info: "#3B82F6",
      "info-strong": "#1E40AF",
    },
  },
  {
    id: "nebula",
    displayName: "Nebula",
    moodFamily: "Dark Vibrant/Expressive",
    sourceReference:
      "Independently derived dark palette — deep violet midnight canvas with a playful, expressive mood family. Real anchors: neutral-50/900 from the source's own deep-violet marketing canvas and white on-dark text; brand-light from the source's own muted-violet accent tier; neutral-100-800 OKLCH-interpolated, anchored against a real one-step-deeper surface stop. KNOWN CORRECTION (implementation-time, documented in contracts/source-token-mapping.contract.md): brand does NOT use the source's literal near-black primary, since that value sits almost exactly as dark as this theme's own neutral-50 and would render brand text/borders/fills nearly invisible against the page — the same dark-theme \"brand needs its own visible register\" issue this catalog's forest/dracula themes already document; a real, visibly-distinct deep-violet accent tier from the same source is used instead, OKLCH-darkened further for brand-dark (needed a genuinely darker press tier than the accent tier alone gives, for white-on-fill button contrast). Semantic pairs (no distinct real anchors documented by the source — its own signature bright accent is explicitly decorative-only per research.md R5, with no direct slot in this catalog's fixed 21-token schema) reuse this catalog's `forest` theme's already-verified dark-theme-compatible semantic values (own inverted-lightness *-strong convention) rather than the light-default's values, which fail contrast against a dark canvas. See specs/027-claude-design-inspired-themes/research.md R3 for the full derivation record.",
    tokens: {
      "brand-light": "#79628C",
      brand: "#422082",
      "brand-dark": "#0F0427",
      "neutral-50": "#1F1633",
      "neutral-100": "#322A46",
      "neutral-200": "#4F4962",
      "neutral-300": "#6A657A",
      "neutral-400": "#847F92",
      "neutral-500": "#9D99A8",
      "neutral-600": "#B6B3BF",
      "neutral-700": "#CECDD4",
      "neutral-800": "#E7E6EA",
      "neutral-900": "#FFFFFF",
      success: "#00A96E",
      "success-strong": "#33C386",
      warning: "#FFBE00",
      "warning-strong": "#FFC500",
      error: "#FF5861",
      "error-strong": "#FF8286",
      info: "#00B5FF",
      "info-strong": "#00BCFF",
    },
  },
];
